// ── Mock Data: 20 fake SF Bay Area education philanthropy contacts ──────────

export interface MockContact {
  id: number;
  first_name: string;
  last_name: string;
  company?: string;
  position?: string;
  city?: string;
  state?: string;
  headline?: string;
  familiarity_rating?: number;
  comms_last_date?: string;
  comms_thread_count?: number;
  ai_capacity_tier?: string;
  ai_capacity_score?: number;
  education_focus_fit?: string;
  sfef_engagement?: Record<string, any>;
  score: number;
  tier: string;
  reasoning: string;
  recommended_approach: string;
  ask_timing: string;
  cultivation_needed: string;
  suggested_ask_range: string;
  personalization_angle: string;
  risk_factors: string[];
  scored_at: string;
}

export interface MockContactDetail extends MockContact {
  email?: string;
  linkedin_url?: string;
  summary?: string;
  comms_closeness?: string;
  comms_momentum?: string;
  comms_reasoning?: string;
  comms_relationship_summary?: string;
  comms_recent_threads?: Array<{
    subject?: string;
    date?: string;
    snippet?: string;
    source?: string;
    direction?: string;
  }>;
  shared_institutions?: Array<{
    name: string;
    type: string;
    overlap: string;
  }>;
  ask_readiness?: Record<string, any>;
  fec_donations?: Record<string, any>;
  real_estate_data?: Record<string, any>;
  ai_proximity_score?: number;
  ai_proximity_tier?: string;
  ai_kindora_prospect_score?: number;
  ai_kindora_prospect_type?: string;
  shared_employers: string[];
  shared_schools: string[];
  shared_boards: string[];
  topics: string[];
  primary_interests: string[];
  personalization_hooks: string[];
  suggested_opener: string;
  best_approach: string;
  talking_points: string[];
}

// ── 3 Ready Now ────────────────────────────────────────────────────────────

const readyNow: MockContact[] = [
  {
    id: 1,
    first_name: 'Margaret',
    last_name: 'Chen',
    company: 'Chen Family Foundation',
    position: 'President',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Education philanthropy leader | Former SFUSD Board',
    familiarity_rating: 4,
    comms_last_date: '2026-02-28',
    comms_thread_count: 14,
    ai_capacity_tier: 'major_donor',
    ai_capacity_score: 92,
    education_focus_fit: 'high',
    sfef_engagement: { is_sfef_donor: true, sfef_total_donated: 25000, sfef_donation_count: 3, crm_roles: ['Donor', 'Board'] },
    score: 94,
    tier: 'ready_now',
    reasoning: 'Active SFEF board member and multi-year donor. Deep personal relationship with executive team. Her foundation prioritizes K-12 literacy in SF. Has already signaled interest in expanding her giving for the upcoming year.',
    recommended_approach: 'in_person',
    ask_timing: 'now',
    cultivation_needed: 'Minimal. Schedule a coffee to share the annual impact report and discuss her foundation\'s aligned priorities for 2026.',
    suggested_ask_range: '$25,000 - $50,000',
    personalization_angle: 'Her daughter attended SFUSD schools through 8th grade. She often references how tutoring programs changed outcomes for her daughter\'s classmates.',
    risk_factors: ['Foundation board meets quarterly; timing around their March meeting is ideal'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 2,
    first_name: 'David',
    last_name: 'Nakamura',
    company: 'Nakamura Ventures',
    position: 'Managing Partner',
    city: 'Palo Alto',
    state: 'CA',
    headline: 'EdTech investor | Stanford GSE Advisory Board',
    familiarity_rating: 3,
    comms_last_date: '2026-02-15',
    comms_thread_count: 8,
    ai_capacity_tier: 'major_donor',
    ai_capacity_score: 88,
    education_focus_fit: 'high',
    sfef_engagement: { is_sfef_donor: true, sfef_total_donated: 15000, sfef_donation_count: 2, crm_roles: ['Donor'] },
    score: 89,
    tier: 'ready_now',
    reasoning: 'Repeat SFEF donor with strong capacity. Invested in three edtech companies focused on underserved schools. Recently posted about the tutoring gap on LinkedIn. Has direct experience with SFEF programming through a portfolio company partnership.',
    recommended_approach: 'personal_email',
    ask_timing: 'now',
    cultivation_needed: 'Send a brief impact update from the winter tutoring cohort, then follow up with a call.',
    suggested_ask_range: '$15,000 - $25,000',
    personalization_angle: 'His portfolio company EduBridge partnered with SFEF on a pilot last fall. He saw the data firsthand.',
    risk_factors: ['End-of-Q1 fund commitments may compete for attention'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 3,
    first_name: 'Sandra',
    last_name: 'Williams',
    company: 'Pacific Heights Consulting',
    position: 'Principal',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Management consultant | Education equity advocate',
    familiarity_rating: 4,
    comms_last_date: '2026-03-02',
    comms_thread_count: 22,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 72,
    education_focus_fit: 'high',
    sfef_engagement: { is_sfef_donor: true, sfef_total_donated: 5000, sfef_donation_count: 4, crm_roles: ['Donor', 'Volunteer'] },
    score: 86,
    tier: 'ready_now',
    reasoning: 'Long-time SFEF volunteer and consistent annual donor. Strong personal connection to the mission through her work with underserved communities. She recently mentioned wanting to "do more" at the last volunteer appreciation event.',
    recommended_approach: 'phone_call',
    ask_timing: 'now',
    cultivation_needed: 'She\'s ready. A direct phone call referencing her volunteer experience and the org\'s growth trajectory will be well-received.',
    suggested_ask_range: '$5,000 - $10,000',
    personalization_angle: 'She tutored 3rd graders at Tenderloin Elementary last semester and saw their reading scores improve by 40%.',
    risk_factors: [],
    scored_at: '2026-03-01T00:00:00Z',
  },
];

// ── 8 Cultivate First ──────────────────────────────────────────────────────

const cultivateFirst: MockContact[] = [
  {
    id: 4,
    first_name: 'Robert',
    last_name: 'Gonzalez',
    company: 'Salesforce',
    position: 'SVP of Social Impact',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Corporate philanthropy | K-12 STEM education',
    familiarity_rating: 2,
    comms_last_date: '2026-01-10',
    comms_thread_count: 3,
    ai_capacity_tier: 'major_donor',
    ai_capacity_score: 85,
    education_focus_fit: 'high',
    score: 78,
    tier: 'cultivate_first',
    reasoning: 'Leads Salesforce\'s education giving portfolio. Has allocated $2M+ to Bay Area K-12 programs. Met at a philanthropy roundtable in January but no deep relationship yet. SFEF\'s tutoring model fits his stated priority of "evidence-based interventions."',
    recommended_approach: 'intro_via_mutual',
    ask_timing: 'after_cultivation',
    cultivation_needed: 'Get a warm intro through the Salesforce Foundation team. Invite to an SFEF school site visit to see the tutoring model in action.',
    suggested_ask_range: '$25,000 - $50,000',
    personalization_angle: 'His team just published a report on corporate-nonprofit partnerships in education. SFEF\'s data-driven approach aligns with their framework.',
    risk_factors: ['Corporate giving cycles may require 6-month lead time', 'Competing asks from other Bay Area ed nonprofits'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 5,
    first_name: 'Jennifer',
    last_name: 'Park',
    company: 'KQED',
    position: 'VP of Education',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Public media education leader | Stanford GSE alum',
    familiarity_rating: 2,
    comms_last_date: '2025-11-20',
    comms_thread_count: 2,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 65,
    education_focus_fit: 'high',
    score: 72,
    tier: 'cultivate_first',
    reasoning: 'Deeply connected to Bay Area education ecosystem. Not a current donor but expressed interest at an event. Her personal network includes several major education funders. Could be a connector and a donor.',
    recommended_approach: 'personal_email',
    ask_timing: 'after_cultivation',
    cultivation_needed: 'Re-engage with a personalized email about SFEF\'s media literacy pilot. Invite to spring gala as a guest.',
    suggested_ask_range: '$2,500 - $5,000',
    personalization_angle: 'KQED\'s education content aligns with SFEF\'s literacy mission. She might see a partnership angle as well as a personal giving opportunity.',
    risk_factors: ['May see this primarily as a partnership pitch rather than a personal ask'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 6,
    first_name: 'Michael',
    last_name: 'Torres',
    company: 'Mission Housing Development',
    position: 'Executive Director',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Affordable housing & community development | Mission District native',
    familiarity_rating: 3,
    comms_last_date: '2026-02-05',
    comms_thread_count: 6,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 58,
    education_focus_fit: 'medium',
    sfef_engagement: { crm_roles: ['Volunteer'] },
    score: 68,
    tier: 'cultivate_first',
    reasoning: 'Strong community ties in the Mission, where several SFEF programs operate. Has volunteered at SFEF events. His org co-locates with two SFEF tutoring sites. Personal giving capacity is moderate but his network influence is high.',
    recommended_approach: 'in_person',
    ask_timing: 'after_cultivation',
    cultivation_needed: 'Grab lunch in the Mission. Discuss how the housing-education intersection creates opportunities for both orgs. Build the relationship before making a formal ask.',
    suggested_ask_range: '$1,000 - $2,500',
    personalization_angle: 'He grew up attending after-school programs in the Mission. SFEF\'s community-based model resonates with his personal story.',
    risk_factors: ['Housing sector is under budget pressure right now'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 7,
    first_name: 'Priya',
    last_name: 'Sharma',
    company: 'Google.org',
    position: 'Education Program Manager',
    city: 'Mountain View',
    state: 'CA',
    headline: 'Tech-for-good | Digital equity in education',
    familiarity_rating: 2,
    comms_last_date: '2026-01-28',
    comms_thread_count: 4,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 70,
    education_focus_fit: 'high',
    score: 74,
    tier: 'cultivate_first',
    reasoning: 'Manages Google.org\'s Bay Area education portfolio. Personal donor to multiple education nonprofits. Met at a conference panel on digital equity. Could open doors to Google.org institutional funding as well.',
    recommended_approach: 'personal_email',
    ask_timing: 'after_cultivation',
    cultivation_needed: 'Share SFEF\'s digital tutoring outcomes data. Propose a site visit where she can see the tech integration firsthand.',
    suggested_ask_range: '$5,000 - $10,000',
    personalization_angle: 'She spoke passionately about first-generation students at the conference. SFEF\'s population is 78% first-gen.',
    risk_factors: ['Google.org has its own grant cycles that may not align with SFEF timing'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 8,
    first_name: 'James',
    last_name: 'Reilly',
    company: 'Reilly Family Office',
    position: 'Director of Philanthropy',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Family office philanthropy | Youth development focus',
    familiarity_rating: 1,
    comms_last_date: undefined,
    comms_thread_count: 0,
    ai_capacity_tier: 'major_donor',
    ai_capacity_score: 95,
    education_focus_fit: 'high',
    score: 71,
    tier: 'cultivate_first',
    reasoning: 'High-capacity family office with a stated focus on youth development and education in SF. No existing relationship but they fund several peer organizations. Worth a strategic introduction.',
    recommended_approach: 'intro_via_mutual',
    ask_timing: 'after_cultivation',
    cultivation_needed: 'Need a warm intro. Their current grantees include Breakthrough SF and Reading Partners — both organizations with board overlap. Secure an introduction, then propose a briefing meeting.',
    suggested_ask_range: '$25,000 - $100,000',
    personalization_angle: 'The Reilly family has roots in SF public education — James\'s mother was a longtime SFUSD teacher.',
    risk_factors: ['No existing relationship', 'Family offices can be slow to onboard new grantees'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 9,
    first_name: 'Lisa',
    last_name: 'Chang',
    company: 'Bay Area Community Foundation',
    position: 'Program Director',
    city: 'Oakland',
    state: 'CA',
    headline: 'Community philanthropy | Equity-centered grantmaking',
    familiarity_rating: 3,
    comms_last_date: '2026-02-20',
    comms_thread_count: 9,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 62,
    education_focus_fit: 'medium',
    score: 67,
    tier: 'cultivate_first',
    reasoning: 'Oversees grantmaking for education equity at BACF. Also a personal donor to education causes. Good relationship but hasn\'t been asked directly for SFEF. Her institutional role gives her outsized influence on where community foundation dollars flow.',
    recommended_approach: 'phone_call',
    ask_timing: 'after_cultivation',
    cultivation_needed: 'Have a candid conversation about SFEF\'s growth plans and how they align with BACF\'s education equity priorities. Dual track: personal ask and institutional awareness.',
    suggested_ask_range: '$2,500 - $5,000',
    personalization_angle: 'She mentioned at a recent dinner that she wishes more orgs had SFEF\'s level of outcomes data.',
    risk_factors: ['Need to navigate the personal/institutional boundary carefully'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 10,
    first_name: 'Anthony',
    last_name: 'Washington',
    company: 'Howard University',
    position: 'Professor of Education Policy',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Education policy researcher | HBCU advocate | Bay Area transplant',
    familiarity_rating: 2,
    comms_last_date: '2026-01-15',
    comms_thread_count: 3,
    ai_capacity_tier: 'grassroots',
    ai_capacity_score: 35,
    education_focus_fit: 'high',
    score: 62,
    tier: 'cultivate_first',
    reasoning: 'Not high capacity but extremely high influence in education policy circles. His research on tutoring effectiveness has been cited by SFEF. Building a relationship could unlock introductions to major funders in the education research community.',
    recommended_approach: 'personal_email',
    ask_timing: 'after_cultivation',
    cultivation_needed: 'Engage on his research. Offer SFEF program data for his next study. Build intellectual partnership before asking for financial support.',
    suggested_ask_range: '$500 - $1,000',
    personalization_angle: 'His most-cited paper focuses on high-dosage tutoring — exactly SFEF\'s model. He\'d be thrilled to see the real-world data.',
    risk_factors: ['Academic salary limits giving capacity', 'May prefer in-kind support over financial'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 11,
    first_name: 'Catherine',
    last_name: 'O\'Brien',
    company: 'Wells Fargo Foundation',
    position: 'Senior Program Officer',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Corporate foundation | Community investment | Education pathways',
    familiarity_rating: 2,
    comms_last_date: '2025-12-10',
    comms_thread_count: 2,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 68,
    education_focus_fit: 'medium',
    score: 64,
    tier: 'cultivate_first',
    reasoning: 'Manages Wells Fargo Foundation\'s education grants in the Bay Area. Has personal giving history to education nonprofits. Brief interaction at a funder briefing last December. Worth cultivating both the personal and institutional relationship.',
    recommended_approach: 'linkedin',
    ask_timing: 'after_cultivation',
    cultivation_needed: 'Connect on LinkedIn with a note referencing the funder briefing. Share SFEF\'s quarterly impact report. Propose a follow-up coffee to discuss alignment.',
    suggested_ask_range: '$2,500 - $5,000',
    personalization_angle: 'Wells Fargo Foundation recently announced a focus on "career-connected learning" — SFEF\'s high school mentoring program is a natural fit.',
    risk_factors: ['Corporate foundation decisions involve multiple stakeholders'],
    scored_at: '2026-03-01T00:00:00Z',
  },
];

// ── 7 Long Term ────────────────────────────────────────────────────────────

const longTerm: MockContact[] = [
  {
    id: 12,
    first_name: 'Thomas',
    last_name: 'Kim',
    company: 'Stripe',
    position: 'Senior Engineering Manager',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Tech leader | First-gen college grad | Volunteer tutor',
    familiarity_rating: 1,
    comms_last_date: '2025-09-15',
    comms_thread_count: 1,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 60,
    education_focus_fit: 'medium',
    score: 48,
    tier: 'long_term',
    reasoning: 'Volunteered once at an SFEF event. Has the personal background that aligns (first-gen, immigrant family) but no established relationship. Tech compensation suggests mid-level capacity. Needs several more touchpoints before an ask.',
    recommended_approach: 'personal_email',
    ask_timing: 'after_reconnection',
    cultivation_needed: 'Invite to volunteer again this spring. Build relationship through shared experience before considering a financial ask. 6+ month timeline.',
    suggested_ask_range: '$1,000 - $2,500',
    personalization_angle: 'He wrote a blog post about how a high school tutor changed his trajectory. That\'s exactly SFEF\'s theory of change.',
    risk_factors: ['Very early in relationship', 'May not remember initial interaction'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 13,
    first_name: 'Rachel',
    last_name: 'Foster',
    company: 'Foster & Associates Law',
    position: 'Partner',
    city: 'Mill Valley',
    state: 'CA',
    headline: 'Education law | School board advisor | Pro bono advocate',
    familiarity_rating: 1,
    comms_last_date: undefined,
    comms_thread_count: 0,
    ai_capacity_tier: 'major_donor',
    ai_capacity_score: 80,
    education_focus_fit: 'medium',
    score: 45,
    tier: 'long_term',
    reasoning: 'High-capacity individual with a professional focus on education law. No existing relationship but she has represented several SFUSD matters and likely knows SFEF by reputation. Worth a long-term cultivation strategy.',
    recommended_approach: 'intro_via_mutual',
    ask_timing: 'after_reconnection',
    cultivation_needed: 'Find a mutual connection (likely through SFUSD board circles). Introduce SFEF\'s work and invite to an event. 6-12 month cultivation.',
    suggested_ask_range: '$5,000 - $15,000',
    personalization_angle: 'Her pro bono work focuses on special education rights — SFEF serves many students with IEPs.',
    risk_factors: ['No existing relationship', 'Marin-based; may focus giving locally'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 14,
    first_name: 'Andrew',
    last_name: 'Martinez',
    company: 'SF Chronicle',
    position: 'Education Reporter',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Investigative journalist | Public education coverage',
    familiarity_rating: 2,
    comms_last_date: '2025-10-05',
    comms_thread_count: 2,
    ai_capacity_tier: 'grassroots',
    ai_capacity_score: 25,
    education_focus_fit: 'high',
    score: 42,
    tier: 'long_term',
    reasoning: 'Low financial capacity but extremely high strategic value. His coverage of SFEF programs could drive awareness and other donations. Has written favorably about SFEF in the past. Relationship is professional, not philanthropic.',
    recommended_approach: 'personal_email',
    ask_timing: 'not_recommended',
    cultivation_needed: 'Maintain as a media relationship. Provide data and stories for his reporting. If he ever moves to philanthropy or a foundation, he\'d be a strong prospect.',
    suggested_ask_range: '$100 - $500',
    personalization_angle: 'His 2025 series on the tutoring crisis in SF schools featured SFEF data prominently.',
    risk_factors: ['Journalist ethics may prevent financial support of orgs they cover', 'Keep professional boundaries clear'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 15,
    first_name: 'Nina',
    last_name: 'Patel',
    company: 'Stanford University',
    position: 'Director of Community Partnerships',
    city: 'Stanford',
    state: 'CA',
    headline: 'University-community engagement | K-16 pipeline programs',
    familiarity_rating: 1,
    comms_last_date: '2025-08-20',
    comms_thread_count: 1,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 55,
    education_focus_fit: 'high',
    score: 44,
    tier: 'long_term',
    reasoning: 'Her role connects Stanford\'s resources to Bay Area K-12 programs. One brief email exchange last summer about a potential volunteer pipeline. Institutional relationship could unlock Stanford volunteers and her personal giving.',
    recommended_approach: 'personal_email',
    ask_timing: 'after_reconnection',
    cultivation_needed: 'Restart the volunteer pipeline conversation. Build institutional partnership first, then explore personal giving over 6-12 months.',
    suggested_ask_range: '$1,000 - $2,500',
    personalization_angle: 'She runs Stanford\'s K-12 outreach. An SFEF partnership would give her students a meaningful placement.',
    risk_factors: ['Stanford bureaucracy can slow partnerships', 'May see SFEF primarily as institutional partner, not personal cause'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 16,
    first_name: 'Walter',
    last_name: 'Hughes',
    company: 'Retired',
    position: 'Former SFUSD Superintendent',
    city: 'San Francisco',
    state: 'CA',
    headline: 'Retired educator | 35 years in public education',
    familiarity_rating: 1,
    comms_last_date: undefined,
    comms_thread_count: 0,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 50,
    education_focus_fit: 'high',
    score: 40,
    tier: 'long_term',
    reasoning: 'Deep knowledge of SF education landscape from 35 years in the system. Retired 2 years ago. No existing relationship but his legacy connections could open doors. Personal giving capacity is moderate.',
    recommended_approach: 'intro_via_mutual',
    ask_timing: 'after_reconnection',
    cultivation_needed: 'Get introduced through current SFUSD leadership. Invite to tour SFEF programs. He\'d appreciate seeing the impact on students he used to serve. 6-12 month cultivation.',
    suggested_ask_range: '$1,000 - $5,000',
    personalization_angle: 'He championed the district\'s tutoring expansion in 2019 — SFEF was one of the providers he selected.',
    risk_factors: ['No existing relationship', 'Retired; may be less engaged than assumed'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 17,
    first_name: 'Emily',
    last_name: 'Yamamoto',
    company: 'Genentech',
    position: 'Director of Community Affairs',
    city: 'South San Francisco',
    state: 'CA',
    headline: 'Biotech community engagement | STEM education advocate',
    familiarity_rating: 1,
    comms_last_date: '2025-07-10',
    comms_thread_count: 1,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 65,
    education_focus_fit: 'medium',
    score: 38,
    tier: 'long_term',
    reasoning: 'Manages Genentech\'s community investment portfolio including STEM education. One brief meeting at a biotech philanthropy event. Could unlock both personal giving and Genentech corporate support, but the relationship is nascent.',
    recommended_approach: 'linkedin',
    ask_timing: 'after_reconnection',
    cultivation_needed: 'Reconnect via LinkedIn. Share SFEF\'s STEM tutoring outcomes. Propose a joint volunteer day at an SFEF school site to build the relationship.',
    suggested_ask_range: '$2,500 - $5,000',
    personalization_angle: 'Genentech\'s SSF campus is two miles from three SFEF school sites. The geographic proximity story writes itself.',
    risk_factors: ['STEM focus may not align perfectly with SFEF\'s literacy emphasis', 'Corporate process is slow'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 18,
    first_name: 'Derek',
    last_name: 'Robinson',
    company: 'Robinson Real Estate Group',
    position: 'CEO',
    city: 'Oakland',
    state: 'CA',
    headline: 'Commercial real estate | Oakland community builder',
    familiarity_rating: 1,
    comms_last_date: undefined,
    comms_thread_count: 0,
    ai_capacity_tier: 'major_donor',
    ai_capacity_score: 82,
    education_focus_fit: 'low',
    score: 35,
    tier: 'long_term',
    reasoning: 'High capacity with Oakland-focused community giving. Education is not his primary philanthropy focus (he gives mainly to housing and workforce development) but there may be an angle through workforce readiness. Very long-term prospect.',
    recommended_approach: 'intro_via_mutual',
    ask_timing: 'after_reconnection',
    cultivation_needed: 'Identify mutual connections in the Oakland philanthropic community. Explore the education-workforce readiness intersection. 12+ month timeline.',
    suggested_ask_range: '$5,000 - $15,000',
    personalization_angle: 'His company sponsors Oakland youth jobs programs. SFEF\'s high school mentoring has a workforce readiness component that could align.',
    risk_factors: ['Oakland-focused giving may not extend to SF-based org', 'Education not his primary cause area', 'No existing relationship'],
    scored_at: '2026-03-01T00:00:00Z',
  },
];

// ── 2 Not a Fit ────────────────────────────────────────────────────────────

const notAFit: MockContact[] = [
  {
    id: 19,
    first_name: 'Karen',
    last_name: 'Mitchell',
    company: 'Mitchell & Associates',
    position: 'Tax Attorney',
    city: 'San Jose',
    state: 'CA',
    headline: 'Tax law | Estate planning | South Bay practice',
    familiarity_rating: 1,
    comms_last_date: undefined,
    comms_thread_count: 0,
    ai_capacity_tier: 'unknown',
    ai_capacity_score: 30,
    education_focus_fit: 'none',
    score: 15,
    tier: 'not_a_fit',
    reasoning: 'No connection to education philanthropy. South Bay tax practice with no apparent overlap. Likely added to contact list through a general networking event. No cultivation path visible.',
    recommended_approach: 'linkedin',
    ask_timing: 'not_recommended',
    cultivation_needed: 'Not recommended. No alignment between her professional focus, geographic giving, or personal interests and SFEF\'s mission.',
    suggested_ask_range: 'N/A',
    personalization_angle: 'None identified.',
    risk_factors: ['No mission alignment', 'No existing relationship', 'Geographic distance'],
    scored_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 20,
    first_name: 'Brian',
    last_name: 'Liu',
    company: 'HealthTech Solutions',
    position: 'CTO',
    city: 'Redwood City',
    state: 'CA',
    headline: 'Healthcare AI | Clinical data platforms',
    familiarity_rating: 0,
    comms_last_date: undefined,
    comms_thread_count: 0,
    ai_capacity_tier: 'mid_level',
    ai_capacity_score: 55,
    education_focus_fit: 'none',
    score: 12,
    tier: 'not_a_fit',
    reasoning: 'No education focus in his professional or philanthropic profile. Healthcare-focused career with no visible connection to K-12 education. Moderate capacity but zero alignment.',
    recommended_approach: 'linkedin',
    ask_timing: 'not_recommended',
    cultivation_needed: 'Not recommended at this time. If he ever signals interest in education (e.g., through a board role or public statement), reassess.',
    suggested_ask_range: 'N/A',
    personalization_angle: 'None identified.',
    risk_factors: ['No mission alignment', 'No existing relationship'],
    scored_at: '2026-03-01T00:00:00Z',
  },
];

// ── Combined list ──────────────────────────────────────────────────────────

export const MOCK_CONTACTS: MockContact[] = [
  ...readyNow,
  ...cultivateFirst,
  ...longTerm,
  ...notAFit,
];

// ── Detail records (extend each contact for the detail sheet) ──────────────

const detailExtensions: Record<number, Partial<MockContactDetail>> = {
  1: {
    email: 'm.chen@chenfamilyfdn.org',
    summary: 'Margaret is a lifelong San Francisco resident and education philanthropist. She served on the SFUSD Board of Education from 2015-2021 and launched the Chen Family Foundation in 2018 with a focus on K-12 literacy in underserved SF neighborhoods.',
    comms_closeness: 'active_inner_circle',
    comms_momentum: 'growing',
    comms_reasoning: 'Regular monthly check-ins, 3 meetings in the past quarter, responsive to emails within 24 hours',
    comms_relationship_summary: 'Deep, trust-based relationship built over 5+ years. She sees SFEF as her primary education giving vehicle.',
    comms_recent_threads: [
      { subject: 'Spring gala table confirmation', date: '2026-02-28', snippet: 'Margaret confirmed a table of 10 for the spring gala', source: 'email', direction: 'bidirectional' },
      { subject: 'Foundation board meeting follow-up', date: '2026-02-15', snippet: 'Shared notes from her foundation board meeting — education is top priority', source: 'email', direction: 'received' },
      { subject: 'Coffee next Tuesday?', date: '2026-02-01', snippet: 'Monthly catch-up scheduled at Ritual Coffee', source: 'email', direction: 'sent' },
    ],
    shared_institutions: [
      { name: 'SFUSD Board of Education', type: 'board', overlap: 'Margaret served 2015-2021' },
      { name: 'SF Foundation', type: 'board', overlap: 'Both serve on education committee' },
    ],
    fec_donations: { total: 45000, recent: [{ recipient: 'SF Literacy Fund PAC', amount: 5000, year: 2024 }] },
    real_estate_data: { properties: [{ address: 'Pacific Heights, SF', zestimate: 4200000 }] },
    ai_proximity_score: 92,
    ai_proximity_tier: 'inner_circle',
    shared_employers: [],
    shared_schools: ['Stanford University'],
    shared_boards: ['SF Foundation'],
    topics: ['K-12 literacy', 'Education equity', 'Family philanthropy', 'Public school advocacy'],
    primary_interests: ['Education', 'Youth development', 'Civic engagement'],
    personalization_hooks: ['Her daughter\'s SFUSD experience', 'Chen Foundation priorities for 2026', 'Spring gala involvement'],
    suggested_opener: 'Margaret, I wanted to share the latest tutoring outcomes before your foundation board meets in March.',
    best_approach: 'In-person coffee meeting',
    talking_points: ['Winter tutoring cohort results', '2026 expansion plans', 'Foundation alignment opportunities'],
  },
  2: {
    email: 'david@nakamuraventures.com',
    summary: 'David is a Stanford GSE-trained education technologist turned venture capitalist. His fund focuses on edtech companies that serve Title I schools.',
    comms_closeness: 'regular_contact',
    comms_momentum: 'stable',
    comms_reasoning: 'Quarterly check-ins, responsive to email. Relationship is warm but primarily professional.',
    comms_recent_threads: [
      { subject: 'EduBridge pilot results', date: '2026-02-15', snippet: 'Shared the SFEF x EduBridge pilot outcomes report', source: 'email', direction: 'sent' },
      { subject: 'Re: Stanford GSE panel', date: '2026-01-20', snippet: 'David suggested co-presenting at the GSE alumni event', source: 'email', direction: 'bidirectional' },
    ],
    shared_institutions: [{ name: 'Stanford GSE', type: 'school', overlap: 'David is an alum and advisory board member' }],
    ai_proximity_score: 75,
    ai_proximity_tier: 'warm',
    shared_employers: [],
    shared_schools: ['Stanford University'],
    shared_boards: [],
    topics: ['EdTech', 'Venture philanthropy', 'Evidence-based education', 'Stanford GSE'],
    primary_interests: ['Education technology', 'Impact investing'],
    personalization_hooks: ['EduBridge pilot partnership', 'Stanford GSE connection', 'Portfolio company alignment'],
    suggested_opener: 'David, the EduBridge pilot data is in — I think you\'ll find the outcomes compelling.',
    best_approach: 'Personal email with data attachment',
    talking_points: ['Pilot outcomes', 'Portfolio company synergies', 'Stanford GSE network'],
  },
  3: {
    email: 'sandra@pacheights.consulting',
    summary: 'Sandra is a management consultant specializing in nonprofit strategy. She has been volunteering with SFEF for four years, primarily as a math tutor at Tenderloin Elementary.',
    comms_closeness: 'active_inner_circle',
    comms_momentum: 'growing',
    comms_reasoning: 'Frequent email and in-person interactions. She initiates contact as often as we do.',
    comms_recent_threads: [
      { subject: 'Volunteer appreciation dinner RSVP', date: '2026-03-02', snippet: 'Sandra RSVP\'d yes and is bringing two friends', source: 'email', direction: 'received' },
      { subject: 'Tutoring session recap', date: '2026-02-22', snippet: 'Amazing session today — her students are crushing fractions', source: 'email', direction: 'received' },
    ],
    shared_institutions: [{ name: 'Bain & Company', type: 'employer', overlap: 'Sandra was at Bain SF 2010-2015' }],
    ai_proximity_score: 85,
    ai_proximity_tier: 'close',
    shared_employers: ['Bain & Company'],
    shared_schools: [],
    shared_boards: [],
    topics: ['Nonprofit strategy', 'K-12 math education', 'Volunteer engagement', 'Education equity'],
    primary_interests: ['Tutoring', 'Nonprofit capacity building'],
    personalization_hooks: ['4 years of tutoring at Tenderloin Elementary', 'Her students\' math score improvements', 'Volunteer appreciation dinner'],
    suggested_opener: 'Sandra, your students\' progress this semester has been incredible. I\'d love to talk about how you can help us reach even more kids.',
    best_approach: 'Phone call',
    talking_points: ['Student outcomes from her tutoring', 'Expansion plans for Tenderloin site', 'Deepening her engagement'],
  },
};

// Generate minimal detail extensions for contacts without custom ones
function getDefaultDetail(contact: MockContact): MockContactDetail {
  return {
    ...contact,
    summary: `${contact.first_name} is based in ${contact.city || 'the Bay Area'} and works at ${contact.company || 'a local organization'}.`,
    comms_closeness: contact.comms_thread_count && contact.comms_thread_count > 5 ? 'regular_contact' : contact.comms_thread_count ? 'occasional' : 'no_history',
    comms_momentum: contact.comms_last_date && contact.comms_last_date > '2026-01-01' ? 'stable' : 'inactive',
    shared_employers: [],
    shared_schools: [],
    shared_boards: [],
    topics: ['Education', 'Bay Area philanthropy'],
    primary_interests: ['Education'],
    personalization_hooks: contact.personalization_angle ? [contact.personalization_angle] : [],
    suggested_opener: `${contact.first_name}, I wanted to introduce you to the work we're doing at SF Education Fund.`,
    best_approach: contact.recommended_approach,
    talking_points: ['SFEF mission and impact', 'Current programs', 'Ways to get involved'],
    ask_readiness: {
      sfef_individual_giving: {
        score: contact.score,
        tier: contact.tier,
        reasoning: contact.reasoning,
        recommended_approach: contact.recommended_approach,
        ask_timing: contact.ask_timing,
        cultivation_needed: contact.cultivation_needed,
        suggested_ask_range: contact.suggested_ask_range,
        personalization_angle: contact.personalization_angle,
        risk_factors: contact.risk_factors,
        scored_at: contact.scored_at,
      },
    },
  };
}

export function getMockContactDetail(id: number): MockContactDetail | null {
  const contact = MOCK_CONTACTS.find((c) => c.id === id);
  if (!contact) return null;

  const base = getDefaultDetail(contact);
  const ext = detailExtensions[id];
  if (ext) {
    return { ...base, ...ext, ask_readiness: { sfef_individual_giving: { score: contact.score, tier: contact.tier, reasoning: contact.reasoning, recommended_approach: contact.recommended_approach, ask_timing: contact.ask_timing, cultivation_needed: contact.cultivation_needed, suggested_ask_range: contact.suggested_ask_range, personalization_angle: contact.personalization_angle, risk_factors: contact.risk_factors, scored_at: contact.scored_at } } };
  }
  return base;
}
